### ISSUE TITLE
Unlocking does not display hidden section

### ISSUE THREAD

**Issue by nicmart84** [ish0w/L0ck-for-plex-media-server#5]
Hi,
I have installed L0ck on my Synology DS214Play using instructions on http://www.beatificabytes.be/wordpress/parental-control-for-plex-on-synology

I manage to lock successfully and unlock using my PIN says it is unlocked but the section hidden still remains hidden.

com.plexapp.plugins.l0ckunl0ck.log: https://gist.github.com/nicmart84/c202008e096ed59bd355

**Comment by ish0w** [comment]
Looks like your Linux distro does not support python timed threading.
Suggest using "0" and regenerating the L0ck plugin or using Plex media
server on another OS Eg:- Mac, Windows, Ubuntu!

**Comment by nicmart84** [comment]
Thing is when I regenerate the plugin, my section still hidden does not
appear! How I can uninstall the plugin and display it?

**Comment by nicmart84** [comment]
I have recreated the section from scratch and when I used 0 as autoL0ck as you suggested, it works now fine :) Thanks for a great plugin!

**Comment by ish0w** [comment]
You needed to locate and manually run the Unl0ck.sh file as suggested
earlier.

If you didn't do that and don't have a backup of the original L0ck.bundle
that you generated the first time your out of luck!

/iSh0w

**Comment by nicmart84** [comment]
I recreated the section at the end. It wasn't one I spent too much time anyway so it was easy enough :)

**Comment by nicmart84** [comment]
I recreated the section at the end. It wasn't one I spent too much time anyway so it was easy enough :)
